import { CategoriaProducto, Estado } from '../types';
import type { IProducto } from '../types';

export const productosIniciales: IProducto[] = [
  {
    id: 1,
    codigo: 'FR001',
    nombre: 'Manzanas Fuji',
    descripcion: 'Manzanas Fuji dulces y crujientes, cultivadas sin pesticidas. Ideales para toda la familia.',
    precio: 3200,
    stock: 45,
    imagen: '/img/manzana.webp',
    categoria: CategoriaProducto.frutas,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-01',
    peso: '1kg',
  },
  {
    id: 2,
    codigo: 'FR002',
    nombre: 'Naranjas Valencia',
    descripcion: 'Naranjas valencianas llenas de vitamina C. Perfectas para zumos frescos y postres naturales.',
    precio: 2800,
    stock: 38,
    imagen: '/img/naranja.webp',
    categoria: CategoriaProducto.frutas,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-02',
    peso: '1kg',
  },
  {
    id: 3,
    codigo: 'FR003',
    nombre: 'Plátanos Cavendish',
    descripcion: 'Plátanos Cavendish dulces y nutritivos, ricos en potasio. Perfectos para desayunos y meriendas saludables.',
    precio: 2200,
    stock: 52,
    imagen: '/img/platanos.webp',
    categoria: CategoriaProducto.frutas,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-03',
    peso: '1kg',
  },
  {
    id: 4,
    codigo: 'VR001',
    nombre: 'Zanahorias Orgánicas',
    descripcion: 'Zanahorias orgánicas dulces y crujientes, ricas en betacaroteno. Excelentes para jugos y ensaladas.',
    precio: 2100,
    stock: 35,
    imagen: '/img/zanahorias.webp',
    categoria: CategoriaProducto.verduras,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-04',
    peso: '500g',
  },
  {
    id: 5,
    codigo: 'VR002',
    nombre: 'Espinacas Frescas',
    descripcion: 'Espinacas orgánicas recién cosechadas, ricas en hierro y vitaminas. Perfectas para ensaladas y smoothies.',
    precio: 2500,
    stock: 28,
    imagen: '/img/espinaca.webp',
    categoria: CategoriaProducto.verduras,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-05',
    peso: '250g',
  },
  {
    id: 6,
    codigo: 'VR003',
    nombre: 'Pimientos Tricolores',
    descripcion: 'Mix de pimientos rojos, amarillos y verdes. Frescos y crujientes, perfectos para ensaladas y guisos.',
    precio: 3500,
    stock: 22,
    imagen: '/img/pimientos.webp',
    categoria: CategoriaProducto.verduras,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-06',
    peso: '500g',
  },
  {
    id: 7,
    codigo: 'PO001',
    nombre: 'Miel Orgánica',
    descripcion: 'Miel pura de flores silvestres, sin procesar y 100% natural. Rica en antioxidantes y minerales.',
    precio: 4500,
    stock: 15,
    imagen: '/img/miel.webp',
    categoria: CategoriaProducto.organicos,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-07',
    peso: '500g',
  },
  {
    id: 8,
    codigo: 'PO003',
    nombre: 'Quinua Orgánica',
    descripcion: 'Quinua orgánica premium, rica en proteínas y aminoácidos esenciales. Perfecta para una dieta balanceada.',
    precio: 3200,
    stock: 20,
    imagen: '/img/quinoa.webp',
    categoria: CategoriaProducto.organicos,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-08',
    peso: '1kg',
  },
  {
    id: 9,
    codigo: 'PL001',
    nombre: 'Leche Entera',
    descripcion: 'Leche entera fresca de vacas alimentadas con pasto. Rica en calcio y proteínas naturales.',
    precio: 1800,
    stock: 25,
    imagen: '/img/leche.webp',
    categoria: CategoriaProducto.lacteos,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-09',
    peso: '1L',
  },
  {
    id: 10,
    codigo: 'PL002',
    nombre: 'Yogurt Natural',
    descripcion: 'Yogurt natural sin azúcar añadida, rico en probióticos. Perfecto para el desayuno.',
    precio: 2200,
    stock: 30,
    imagen: '/img/yogurt.webp',
    categoria: CategoriaProducto.lacteos,
    isActivo: Estado.activo,
    estado: Estado.activo,
    fechaCreacion: '2025-01-10',
    peso: '500g',
  },
];
